name: 检查合并冲突

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, master]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 检查合并冲突标记
        run: |
            echo "发现合并冲突标记！请解决冲突后再提交。"
            exit 1
          fi 